/* Generated by Yosys 0.8 (git sha1 b4e5e37, clang 8.0.1 -fPIC -Os) */

module xnor5_1(opcode, func, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input [4:0] func;
  input [4:0] opcode;
  output out;
  wire xor0;
  wire xor1;
  wire xor2;
  wire xor3;
  wire xor4;
  assign _00_ = xor0 & xor1;
  assign _01_ = _00_ & xor2;
  assign _02_ = _01_ & xor3;
  assign out = _02_ & xor4;
  assign xor3 = ~ _03_;
  assign xor4 = ~ _04_;
  assign xor0 = ~ _05_;
  assign xor1 = ~ _06_;
  assign xor2 = ~ _07_;
  assign _03_ = opcode[3] ^ func[3];
  assign _04_ = opcode[4] ^ func[4];
  assign _05_ = opcode[0] ^ func[0];
  assign _06_ = opcode[1] ^ func[1];
  assign _07_ = opcode[2] ^ func[2];
endmodule
